### ISSUE TITLE
Sending multiline motion fails on Neovim v0.3.1

### ISSUE THREAD

**Issue by Perlence** [Vigemus/iron.nvim#87]
I'm using Neovim v0.3.1 and python3-neovim v0.2.6, I get this exception when sending motions like `ii`, `ap`:

```
error caught in async handler '/home/sviatoslav/.config/nvim/plugged/iron.nvim/rplugin/python3/iron:function:IronSendMotion [['line'], [1, 1]]'
Traceback (most recent call last):
  File "/home/sviatoslav/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/__init__.py", line 157, in send_motion_to_repl
    self.call('winrestview', cur_buf.vars['iron_cursor_pos'])
  File "/home/sviatoslav/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/base.py", line 154, in call
    return self.nvim.call(cmd, *args)
  File "/home/sviatoslav/.local/share/virtualenvs/project-c9MqqoZ0/lib/python3.6/site-packages/neovim/api/nvim.py", line 284, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/home/sviatoslav/.local/share/virtualenvs/project-c9MqqoZ0/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/sviatoslav/.local/share/virtualenvs/project-c9MqqoZ0/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E474: Invalid argument'
```

This same works fine in Neovim v0.2.2.

**Comment by hkupty** [comment]
Weird. I need to take a  deeper look.
Two things, though:
1 - I'm not familiar with this `ii` motion. Is it defined by other plugins? If so, does iron breaks with build-in motions like `ap` or `$`?
2 - Even though I know it's a bit broken at the moment, I'm working on a lua rewrite that *mostly* works. Would you mind testing against it as well to see if the error persists? Take ea look at #85 for more details.

I'm asking that so I can isolate where the issue might be. If it's in the RPC mechanism, the new lua backend will solve it. If it's in the binding between the motion and the function, it might be something wrong with iron itself, so I'll need to check this on the lua version as well.

Thanks for the issue. I hope we can solve this as soon as possible, so such bugs won't get in your way anymore.

Cheers,
Henry

**Comment by Perlence** [comment]
Yep, it doesn't work with `ap` as well. `ii` is a third-party indent-wise motion. As far as I remember it works for `$`. I'll try the lua version soon, thanks.

**Comment by hkupty** [comment]
Now that the lua branch is merged, can you check if the issue still persists?

Cheers,
Henry John Kupty

**Comment by Perlence** [comment]
@hkupty No issues now, works for me.
